// REDHOOD 서비스 워커 — 오프라인 캐시
// ⚠ 판을 바꾸면 CACHE 번호를 반드시 +1 (runbook 규칙)
const CACHE = 'redhood-v98';
const ASSETS = [
  './',
  './index.html',
  './manifest.json',
  './css/style.css',
  './assets/fonts/song-myung/index.css',
  './assets/fonts/song-myung/files/song-myung-korean-400-normal.woff2',
  './js/main.js',
  './js/data.js',
  './js/yahtzee.js',
  './js/engine.js',
  './js/run.js',
  './data/dice.json',
  './data/relics.json',
  './data/scoring.json',
  './data/enemies.json',
  './data/act1.json',
  './data/events.json',
  './data/acts.json',
  './assets/dice/pip1.png',
  './assets/dice/pip2.png',
  './assets/dice/pip3.png',
  './assets/dice/pip4.png',
  './assets/dice/pip5.png',
  './assets/dice/pip6.png',
  './assets/dice/normal1.png',
  './assets/dice/normal2.png',
  './assets/dice/normal3.png',
  './assets/dice/normal4.png',
  './assets/dice/normal5.png',
  './assets/dice/normal6.png',
  './assets/dice/gold1.png',
  './assets/dice/gold2.png',
  './assets/dice/gold3.png',
  './assets/dice/gold4.png',
  './assets/dice/gold5.png',
  './assets/dice/gold6.png',
  './assets/dice/cursed1.png',
  './assets/dice/cursed2.png',
  './assets/dice/cursed3.png',
  './assets/dice/cursed4.png',
  './assets/dice/cursed5.png',
  './assets/dice/cursed6.png',
  './assets/dice/fang1.png',
  './assets/dice/fang2.png',
  './assets/dice/fang3.png',
  './assets/dice/fang4.png',
  './assets/dice/fang5.png',
  './assets/dice/fang6.png',
  './assets/dice/straw1.png',
  './assets/dice/straw2.png',
  './assets/dice/straw3.png',
  './assets/dice/straw4.png',
  './assets/dice/straw5.png',
  './assets/dice/straw6.png',
  './assets/dice/ember1.png',
  './assets/dice/ember2.png',
  './assets/dice/ember3.png',
  './assets/dice/ember4.png',
  './assets/dice/ember5.png',
  './assets/dice/ember6.png',
  './assets/dice/moonlit1.png',
  './assets/dice/moonlit2.png',
  './assets/dice/moonlit3.png',
  './assets/dice/moonlit4.png',
  './assets/dice/moonlit5.png',
  './assets/dice/moonlit6.png',
  './assets/dice/bramble1.png',
  './assets/dice/bramble2.png',
  './assets/dice/bramble3.png',
  './assets/dice/bramble4.png',
  './assets/dice/bramble5.png',
  './assets/dice/bramble6.png',
  './assets/dice/lead1.png',
  './assets/dice/lead2.png',
  './assets/dice/lead3.png',
  './assets/dice/lead4.png',
  './assets/dice/lead5.png',
  './assets/dice/lead6.png',
  './assets/dice/even1.png',
  './assets/dice/even2.png',
  './assets/dice/even3.png',
  './assets/dice/even4.png',
  './assets/dice/even5.png',
  './assets/dice/even6.png',
  './assets/dice/odd1.png',
  './assets/dice/odd2.png',
  './assets/dice/odd3.png',
  './assets/dice/odd4.png',
  './assets/dice/odd5.png',
  './assets/dice/odd6.png',
  './assets/dice/high1.png',
  './assets/dice/high2.png',
  './assets/dice/high3.png',
  './assets/dice/high4.png',
  './assets/dice/high5.png',
  './assets/dice/high6.png',
  './assets/dice/ace1.png',
  './assets/dice/ace2.png',
  './assets/dice/ace3.png',
  './assets/dice/ace4.png',
  './assets/dice/ace5.png',
  './assets/dice/ace6.png',
  './assets/icons/status_strength.png',
  './assets/icons/status_focus.png',
  './assets/icons/status_regen.png',
  './assets/icons/status_block.png',
  './assets/icons/status_weak.png',
  './assets/icons/status_bleed.png',
  './assets/icons/status_vulnerable.png',
  './assets/icons/status_confuse.png',
  './assets/icons/intent_attack.png',
  './assets/icons/intent_defend.png',
  './assets/icons/intent_confuse.png',
  './assets/icons/intent_empower.png',
  './assets/icons/intent_heal.png',
  './assets/icons/intent_unknown.png',
  './assets/icons/node_battle.png',
  './assets/icons/node_elite.png',
  './assets/icons/node_rest.png',
  './assets/icons/node_event.png',
  './assets/icons/node_shop.png',
  './assets/icons/node_boss.png',
  './assets/icons/weapon_gun.png',
  './assets/icons/weapon_scythe.png',
  './assets/icons/weapon_lantern.png',
  './assets/icons/weapon_shovel.png',
  './assets/icons/weapon_crossbow.png',
  './assets/icons/weapon_dagger.png',
  './assets/ui/node_plate.png',
  './assets/ui/btn_primary.png',
  './assets/ui/btn_ghost.png',
  './assets/ui/paper_row.png',
  './assets/ui/frame_modal.jpg',
  './assets/ui/tex_cloth.jpg',
  './assets/ui/tex_wood.jpg',
  './assets/ui/logo.png',
  './assets/ui/nameplate.png',
  './assets/ui/die_pad.png',
  './assets/ui/hpbar_player.png',
  './assets/ui/hpbar_normal.png',
  './assets/ui/hpbar_elite.png',
  './assets/ui/hpbar_boss.png',
  './assets/ui/gauge_red.jpg',
  './assets/ui/gauge_shield.jpg',
  './assets/icons/doodle_battle.png',
  './assets/icons/doodle_elite.png',
  './assets/icons/doodle_rest.png',
  './assets/icons/doodle_event.png',
  './assets/icons/doodle_shop.png',
  './assets/icons/doodle_boss.png',
  './assets/bg/bg_map.jpg',
  './assets/bg/bg_forest.jpg',
  './assets/bg/bg_stream.jpg',
  './assets/bg/bg_cabin.jpg',
  './assets/enemies/stray_dog.png',
  './assets/enemies/wolf.png',
  './assets/enemies/crow.png',
  './assets/enemies/will_o_wisp.png',
  './assets/enemies/forest_spider.png',
  './assets/enemies/thorn_bush.png',
  './assets/enemies/twig_golem.png',
  './assets/enemies/brook_sprite.png',
  './assets/enemies/leech.png',
  './assets/enemies/rat_swarm.png',
  './assets/enemies/living_broom.png',
  './assets/enemies/alpha_dog.png',
  './assets/enemies/old_pike.png',
  './assets/enemies/cellar_thing.png',
  './assets/enemies/old_teddy.png',
  './assets/enemies/river_hag.png',
  './assets/enemies/swamp_king.png',
  './assets/enemies/fog_mother.png',
  './assets/enemies/the_buried.png',
  './assets/enemies/bog_toad.png',
  './assets/enemies/mosquito_swarm.png',
  './assets/enemies/mist_wraith.png',
  './assets/enemies/pale_stag.png',
  './assets/enemies/skeleton.png',
  './assets/enemies/grave_worm.png',
  './assets/enemies/mud_golem.png',
  './assets/enemies/headless_knight.png',
  './assets/enemies/grave_keeper.png',
  './assets/enemies/nightmare_hare.png',
  './assets/enemies/floating_eye.png',
  './assets/enemies/dream_moth.png',
  './assets/enemies/whisper_polyp.png',
  './assets/enemies/faceless_cultist.png',
  './assets/enemies/screaming_stone.png',
  './assets/enemies/hollow_priest.png',
  './assets/enemies/choir_ghost.png',
  './assets/enemies/candle_swarm.png',
  './assets/enemies/sandman.png',
  './assets/enemies/hill_tentacle.png',
  './assets/enemies/bell_ringer.png',
  './assets/enemies/lucid_king.png',
  './assets/enemies/the_maw.png',
  './assets/enemies/false_saint.png',
  './assets/enemies/nameless_dread.png',
  './assets/npc/redhood.png',
  './assets/npc/peddler.png',
  './assets/npc/signpost.png',
  './assets/npc/dwarf.png',
  './assets/npc/altar.png',
  './assets/npc/stream_chest.png',
  './assets/npc/swamp_light.png',
  './assets/npc/voice_in_mist.png',
  './assets/npc/open_grave.png',
  './assets/npc/sweet_dream.png',
  './assets/npc/whispering_stone.png',
  './assets/npc/confession.png',
  './assets/dice/gold.png',
  './assets/dice/cursed.png',
  './assets/dice/fang.png',
  './assets/icon-192.png',
  './assets/icon-512.png',
];

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(ASSETS)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

// v0.63: 두 갈래 전략
//  · 코드·데이터(html/css/js/json) — 네트워크 강제 재요청. 판을 올리면 즉시 반영된다.
//  · 그림·폰트 등 자산 — 캐시 우선. 재렌더마다 네트워크로 다시 받느라
//    화면이 깜빡이던 문제의 근본 원인이었다. 자산은 판이 바뀌면 CACHE 교체로 갱신된다.
self.addEventListener('fetch', (e) => {
  if (e.request.method !== 'GET') return;
  const u = new URL(e.request.url);
  const isCode = /\.(?:html|css|js|json)$/.test(u.pathname) || u.pathname.endsWith('/');
  if (isCode) {
    e.respondWith(
      fetch(new Request(e.request, { cache: 'reload' }))
        .then(res => { const copy = res.clone(); caches.open(CACHE).then(c => c.put(e.request, copy)); return res; })
        .catch(() => caches.match(e.request, { ignoreSearch: true }))
    );
    return;
  }
  e.respondWith(
    caches.match(e.request, { ignoreSearch: true }).then(hit => hit || fetch(e.request).then(res => {
      const copy = res.clone();
      caches.open(CACHE).then(c => c.put(e.request, copy));
      return res;
    }))
  );
});
