// REDHOOD 서비스 워커 — 오프라인 캐시
// ⚠ 판을 바꾸면 CACHE 번호를 반드시 +1 (runbook 규칙)
const CACHE = 'redhood-v53';
const ASSETS = [
  './',
  './index.html',
  './manifest.json',
  './css/style.css',
  './assets/fonts/song-myung/index.css',
  './js/main.js',
  './js/data.js',
  './js/yahtzee.js',
  './js/engine.js',
  './js/run.js',
  './data/dice.json',
  './data/relics.json',
  './data/scoring.json',
  './data/enemies.json',
  './data/act1.json',
  './data/events.json',
  './data/acts.json',
  './assets/dice/pip1.png',
  './assets/dice/pip2.png',
  './assets/dice/pip3.png',
  './assets/dice/pip4.png',
  './assets/dice/pip5.png',
  './assets/dice/pip6.png',
  './assets/dice/normal1.png',
  './assets/dice/normal2.png',
  './assets/dice/normal3.png',
  './assets/dice/normal4.png',
  './assets/dice/normal5.png',
  './assets/dice/normal6.png',
  './assets/dice/gold1.png',
  './assets/dice/gold2.png',
  './assets/dice/gold3.png',
  './assets/dice/gold4.png',
  './assets/dice/gold5.png',
  './assets/dice/gold6.png',
  './assets/dice/cursed1.png',
  './assets/dice/cursed2.png',
  './assets/dice/cursed3.png',
  './assets/dice/cursed4.png',
  './assets/dice/cursed5.png',
  './assets/dice/cursed6.png',
  './assets/dice/fang1.png',
  './assets/dice/fang2.png',
  './assets/dice/fang3.png',
  './assets/dice/fang4.png',
  './assets/dice/fang5.png',
  './assets/dice/fang6.png',
  './assets/dice/straw1.png',
  './assets/dice/straw2.png',
  './assets/dice/straw3.png',
  './assets/dice/straw4.png',
  './assets/dice/straw5.png',
  './assets/dice/straw6.png',
  './assets/dice/ember1.png',
  './assets/dice/ember2.png',
  './assets/dice/ember3.png',
  './assets/dice/ember4.png',
  './assets/dice/ember5.png',
  './assets/dice/ember6.png',
  './assets/dice/moonlit1.png',
  './assets/dice/moonlit2.png',
  './assets/dice/moonlit3.png',
  './assets/dice/moonlit4.png',
  './assets/dice/moonlit5.png',
  './assets/dice/moonlit6.png',
  './assets/dice/bramble1.png',
  './assets/dice/bramble2.png',
  './assets/dice/bramble3.png',
  './assets/dice/bramble4.png',
  './assets/dice/bramble5.png',
  './assets/dice/bramble6.png',
  './assets/dice/lead1.png',
  './assets/dice/lead2.png',
  './assets/dice/lead3.png',
  './assets/dice/lead4.png',
  './assets/dice/lead5.png',
  './assets/dice/lead6.png',
  './assets/dice/even1.png',
  './assets/dice/even2.png',
  './assets/dice/even3.png',
  './assets/dice/even4.png',
  './assets/dice/even5.png',
  './assets/dice/even6.png',
  './assets/dice/odd1.png',
  './assets/dice/odd2.png',
  './assets/dice/odd3.png',
  './assets/dice/odd4.png',
  './assets/dice/odd5.png',
  './assets/dice/odd6.png',
  './assets/dice/high1.png',
  './assets/dice/high2.png',
  './assets/dice/high3.png',
  './assets/dice/high4.png',
  './assets/dice/high5.png',
  './assets/dice/high6.png',
  './assets/dice/ace1.png',
  './assets/dice/ace2.png',
  './assets/dice/ace3.png',
  './assets/dice/ace4.png',
  './assets/dice/ace5.png',
  './assets/dice/ace6.png',
  './assets/icons/status_strength.png',
  './assets/icons/status_focus.png',
  './assets/icons/status_regen.png',
  './assets/icons/status_block.png',
  './assets/icons/status_weak.png',
  './assets/icons/status_bleed.png',
  './assets/icons/status_vulnerable.png',
  './assets/icons/status_confuse.png',
  './assets/icons/intent_attack.png',
  './assets/icons/intent_defend.png',
  './assets/icons/intent_confuse.png',
  './assets/icons/intent_empower.png',
  './assets/icons/intent_heal.png',
  './assets/icons/intent_unknown.png',
  './assets/icons/node_battle.png',
  './assets/icons/node_elite.png',
  './assets/icons/node_rest.png',
  './assets/icons/node_event.png',
  './assets/icons/node_shop.png',
  './assets/icons/node_boss.png',
  './assets/icons/weapon_gun.png',
  './assets/icons/weapon_scythe.png',
  './assets/icons/weapon_lantern.png',
  './assets/icons/weapon_shovel.png',
  './assets/icons/weapon_crossbow.png',
  './assets/icons/weapon_dagger.png',
  './assets/ui/node_plate.png',
  './assets/ui/btn_primary.png',
  './assets/ui/btn_ghost.png',
  './assets/ui/paper_row.png',
  './assets/ui/frame_modal.jpg',
  './assets/ui/tex_cloth.jpg',
  './assets/ui/tex_wood.jpg',
  './assets/ui/logo.png',
  './assets/ui/nameplate.png',
  './assets/ui/die_pad.png',
  './assets/icons/doodle_battle.png',
  './assets/icons/doodle_elite.png',
  './assets/icons/doodle_rest.png',
  './assets/icons/doodle_event.png',
  './assets/icons/doodle_shop.png',
  './assets/icons/doodle_boss.png',
  './assets/bg/bg_map.jpg',
  './assets/bg/bg_forest.jpg',
  './assets/enemies/stray_dog.png',
  './assets/npc/peddler.png',
  './assets/npc/signpost.png',
  './assets/dice/gold.png',
  './assets/dice/cursed.png',
  './assets/dice/fang.png',
  './assets/icon-192.png',
  './assets/icon-512.png',
];

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(ASSETS)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

// 네트워크 우선, 실패 시 캐시 (개발 중 최신 반영 우선. 오프라인이면 캐시로 동작)
self.addEventListener('fetch', (e) => {
  if (e.request.method !== 'GET') return;
  e.respondWith(
    fetch(e.request)
      .then(res => {
        const copy = res.clone();
        caches.open(CACHE).then(c => c.put(e.request, copy));
        return res;
      })
      .catch(() => caches.match(e.request, { ignoreSearch: true }))
  );
});
