<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../Assets/Tests/EditMode/**/*.cs" />
    <Compile Include="Program.cs" />
    <ProjectReference Include="../Redhood.Core.csproj" />
    <PackageReference Include="NUnitLite" Version="3.14.0" />
  </ItemGroup>
</Project>
